/**
 * 官方 GCD 技能（60 个）。
 *
 * 单位约定：秒。normalize 阶段转整数毫秒并强制校验 16ms 对齐（裁决 4）。
 * 因 1000ms % 16 = 8，Buff 时长只能用偶数秒；GCD 时长用 1.6/2.4/3.2/4.0。
 *
 * 设计意图：六大流派各 10 个技能，形成不同的序列构筑方向。
 *   斩击（physical）  — 稳定单体输出，连击加成
 *   烈焰（fire）      — 高倍率但有自伤/引燃机制
 *   霜寒（frost）     — 减速与控制，配合减防
 *   幽影（shadow）    — 吸血续航
 *   雷霆（thunder）   — 群体伤害
 *   秩序（order）     — 增益与治疗
 */

import { SKILL_RANGE, SKILL_TYPE } from '../../../core/constants.js';
import { CD, GCD, damageBuffSkill, damageSkill, drainSkill, healSkill, when } from './helpers.js';

/** 流派 1：斩击 — 稳定单体，倍率随 GCD 时长线性增长 */
const bladeSkills = [
  damageSkill({
    id: 'blade.jab',
    name: '刺击',
    description: '最快的起手技，倍率低但硬直短。',
    gcdCost: GCD.FAST,
    multiplier: 0.75,
    tags: ['physical', 'opener'],
  }),
  damageSkill({
    id: 'blade.slash',
    name: '斩击',
    description: '标准单体攻击，作为序列骨架。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.2,
    tags: ['physical', 'filler'],
  }),
  damageSkill({
    id: 'blade.cleave',
    name: '劈砍',
    description: '重型单体攻击，硬直较长。',
    gcdCost: GCD.SLOW,
    multiplier: 1.75,
    tags: ['physical'],
  }),
  damageSkill({
    id: 'blade.executioner',
    name: '斩首',
    description: '仅在目标生命低于 30% 时可用，倍率极高。',
    gcdCost: GCD.SLOW,
    multiplier: 3.2,
    condition: when.targetHpBelow(0.3),
    tags: ['physical', 'execute'],
  }),
  damageBuffSkill({
    id: 'blade.riposte',
    name: '还击',
    description: '造成伤害并叠加"战意"，提升后续技能表现。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.1,
    buffId: 'blade.momentum',
    stacks: 1,
    buffDuration: 12,
    buffOnTarget: false,
    tags: ['physical', 'combo'],
  }),
  damageSkill({
    id: 'blade.momentumStrike',
    name: '势断',
    description: '需要"战意"在场，倍率显著提升。',
    gcdCost: GCD.NORMAL,
    multiplier: 2.0,
    condition: when.hasBuff('blade.momentum'),
    tags: ['physical', 'combo'],
  }),
  damageSkill({
    id: 'blade.whirl',
    name: '横扫',
    description: '攻击全部敌人，单体倍率偏低。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.85,
    tags: ['physical', 'aoe'],
  }),
  damageSkill({
    id: 'blade.pierce',
    name: '贯穿',
    description: '无视部分防御的穿刺攻击。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.35,
    tags: ['physical', 'pierce'],
  }),
  damageSkill({
    id: 'blade.overhead',
    name: '力劈',
    description: '最重的单体斩击，硬直很长。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.4,
    tags: ['physical', 'heavy'],
  }),
  damageBuffSkill({
    id: 'blade.disarm',
    name: '缴械',
    description: '削弱目标攻势。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.9,
    buffId: 'debuff.weakened',
    buffDuration: 12,
    tags: ['physical', 'debuff'],
  }),
];

/** 流派 2：烈焰 — 高倍率，引燃叠加 */
const fireSkills = [
  damageSkill({
    id: 'fire.spark',
    name: '火花',
    description: '低耗火系起手。',
    gcdCost: GCD.FAST,
    multiplier: 0.8,
    tags: ['fire'],
  }),
  damageBuffSkill({
    id: 'fire.ignite',
    name: '点燃',
    description: '造成伤害并施加"引燃"。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.0,
    buffId: 'debuff.burning',
    buffDuration: 12,
    tags: ['fire', 'dot'],
  }),
  damageSkill({
    id: 'fire.fireball',
    name: '火球',
    description: '标准火系单体法术。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.4,
    tags: ['fire'],
  }),
  damageSkill({
    id: 'fire.detonate',
    name: '引爆',
    description: '目标带有"引燃"时倍率翻倍。',
    gcdCost: GCD.SLOW,
    multiplier: 2.6,
    tags: ['fire', 'combo'],
  }),
  damageSkill({
    id: 'fire.flameWave',
    name: '炎浪',
    description: '波及全部敌人。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.95,
    tags: ['fire', 'aoe'],
  }),
  damageSkill({
    id: 'fire.conflagration',
    name: '烈焰狂燃',
    description: '极高倍率，硬直很长。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.8,
    tags: ['fire', 'heavy'],
  }),
  damageBuffSkill({
    id: 'fire.emberShield',
    name: '余烬护罩',
    description: '造成伤害并为自身附加"炽热"增益。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.95,
    buffId: 'buff.blazing',
    buffDuration: 16,
    buffOnTarget: false,
    tags: ['fire', 'buff'],
  }),
  damageSkill({
    id: 'fire.pyreLance',
    name: '炎枪',
    description: '持有"炽热"时威力提升。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.9,
    condition: when.hasBuff('buff.blazing'),
    tags: ['fire', 'combo'],
  }),
  damageSkill({
    id: 'fire.scorchAll',
    name: '焦土',
    description: '敌人两个以上时才值得使用。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.15,
    condition: when.enemiesAtLeast(2),
    tags: ['fire', 'aoe'],
  }),
  damageSkill({
    id: 'fire.lastEmber',
    name: '残烬',
    description: '自身生命低于 40% 时倍率大幅提升。',
    gcdCost: GCD.NORMAL,
    multiplier: 2.2,
    condition: when.hpBelow(0.4),
    tags: ['fire', 'desperate'],
  }),
];

/** 流派 3：霜寒 — 减防与控制 */
const frostSkills = [
  damageSkill({
    id: 'frost.shard',
    name: '冰棱',
    description: '快速霜系起手。',
    gcdCost: GCD.FAST,
    multiplier: 0.78,
    tags: ['frost'],
  }),
  damageBuffSkill({
    id: 'frost.chill',
    name: '寒缚',
    description: '造成伤害并施加"冰缓"，降低目标行动效率。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.0,
    buffId: 'debuff.chilled',
    buffDuration: 12,
    tags: ['frost', 'control'],
  }),
  damageSkill({
    id: 'frost.iceLance',
    name: '冰枪',
    description: '标准霜系单体法术。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.35,
    tags: ['frost'],
  }),
  damageSkill({
    id: 'frost.shatter',
    name: '碎冰',
    description: '对被"冰缓"的目标造成额外伤害。',
    gcdCost: GCD.SLOW,
    multiplier: 2.3,
    tags: ['frost', 'combo'],
  }),
  damageSkill({
    id: 'frost.blizzard',
    name: '暴雪',
    description: '席卷全场的霜系群攻。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.9,
    tags: ['frost', 'aoe'],
  }),
  damageBuffSkill({
    id: 'frost.brittle',
    name: '脆化',
    description: '大幅降低目标防御。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.85,
    buffId: 'debuff.brittle',
    buffDuration: 16,
    tags: ['frost', 'debuff'],
  }),
  damageSkill({
    id: 'frost.glacialSpike',
    name: '冰川刺',
    description: '重型霜系攻击。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.55,
    tags: ['frost', 'heavy'],
  }),
  damageBuffSkill({
    id: 'frost.frostArmor',
    name: '霜甲',
    description: '为自身附加减伤增益。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.7,
    buffId: 'buff.frostArmor',
    buffDuration: 20,
    buffOnTarget: false,
    tags: ['frost', 'defensive'],
  }),
  damageSkill({
    id: 'frost.deepFreeze',
    name: '深度冻结',
    description: '仅在敌人较多时使用效率最高。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.1,
    condition: when.enemiesAtLeast(3),
    tags: ['frost', 'aoe'],
  }),
  damageSkill({
    id: 'frost.absoluteZero',
    name: '绝对零度',
    description: '战斗持续 30 秒后解锁的强力技能。',
    gcdCost: GCD.HEAVY,
    multiplier: 3.0,
    condition: when.afterSeconds(30),
    tags: ['frost', 'lategame'],
  }),
];

/** 流派 4：幽影 — 吸血续航 */
const shadowSkills = [
  drainSkill({
    id: 'shadow.touch',
    name: '幽触',
    description: '轻微吸血。',
    gcdCost: GCD.FAST,
    multiplier: 0.7,
    drainRatio: 0.3,
    tags: ['shadow', 'drain'],
  }),
  drainSkill({
    id: 'shadow.siphon',
    name: '汲取',
    description: '标准吸血技能。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.1,
    drainRatio: 0.45,
    tags: ['shadow', 'drain'],
  }),
  drainSkill({
    id: 'shadow.devour',
    name: '吞噬',
    description: '高倍率吸血，硬直较长。',
    gcdCost: GCD.SLOW,
    multiplier: 1.6,
    drainRatio: 0.55,
    tags: ['shadow', 'drain'],
  }),
  drainSkill({
    id: 'shadow.desperateFeed',
    name: '垂死渴血',
    description: '生命低于 35% 时吸血比例极高。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.3,
    drainRatio: 1.0,
    condition: when.hpBelow(0.35),
    tags: ['shadow', 'drain', 'desperate'],
  }),
  damageSkill({
    id: 'shadow.bolt',
    name: '暗影箭',
    description: '纯粹的暗影伤害。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.3,
    tags: ['shadow'],
  }),
  damageBuffSkill({
    id: 'shadow.curse',
    name: '诅咒',
    description: '施加"衰败"，持续削弱目标。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.9,
    buffId: 'debuff.decay',
    buffDuration: 16,
    tags: ['shadow', 'debuff'],
  }),
  damageSkill({
    id: 'shadow.nightfall',
    name: '夜幕',
    description: '暗影群体攻击。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.88,
    tags: ['shadow', 'aoe'],
  }),
  drainSkill({
    id: 'shadow.harvest',
    name: '收割',
    description: '对全部敌人吸血。',
    gcdCost: GCD.HEAVY,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.0,
    drainRatio: 0.35,
    tags: ['shadow', 'aoe', 'drain'],
  }),
  damageSkill({
    id: 'shadow.voidRend',
    name: '虚空裂',
    description: '重型暗影单体攻击。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.5,
    tags: ['shadow', 'heavy'],
  }),
  damageBuffSkill({
    id: 'shadow.shroud',
    name: '暗影帷幕',
    description: '为自身附加"隐蔽"。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.75,
    buffId: 'buff.shrouded',
    buffDuration: 16,
    buffOnTarget: false,
    tags: ['shadow', 'defensive'],
  }),
];

/** 流派 5：雷霆 — 群体与随机打击 */
const thunderSkills = [
  damageSkill({
    id: 'thunder.spark',
    name: '雷火星',
    description: '快速雷系起手。',
    gcdCost: GCD.FAST,
    multiplier: 0.82,
    tags: ['thunder'],
  }),
  damageSkill({
    id: 'thunder.bolt',
    name: '雷击',
    description: '标准雷系单体。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.32,
    tags: ['thunder'],
  }),
  damageSkill({
    id: 'thunder.chain',
    name: '连锁闪电',
    description: '击中全部敌人。',
    gcdCost: GCD.NORMAL,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.8,
    tags: ['thunder', 'aoe'],
  }),
  damageSkill({
    id: 'thunder.arcRandom',
    name: '乱雷',
    description: '随机命中一名敌人，倍率较高。',
    gcdCost: GCD.NORMAL,
    range: SKILL_RANGE.RANDOM_ENEMY,
    multiplier: 1.75,
    tags: ['thunder', 'random'],
  }),
  damageSkill({
    id: 'thunder.stormfront',
    name: '风暴前锋',
    description: '强力群体雷击。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.05,
    tags: ['thunder', 'aoe'],
  }),
  damageBuffSkill({
    id: 'thunder.overcharge',
    name: '过载',
    description: '为自身叠加"雷充"。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.9,
    buffId: 'buff.charged',
    stacks: 1,
    buffDuration: 12,
    buffOnTarget: false,
    tags: ['thunder', 'buff'],
  }),
  damageSkill({
    id: 'thunder.dischargeAll',
    name: '放电',
    description: '持有"雷充"时对全场造成大量伤害。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.5,
    condition: when.hasBuff('buff.charged'),
    tags: ['thunder', 'aoe', 'combo'],
  }),
  damageSkill({
    id: 'thunder.judgment',
    name: '雷罚',
    description: '重型雷系单体。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.6,
    tags: ['thunder', 'heavy'],
  }),
  damageBuffSkill({
    id: 'thunder.staticField',
    name: '静电场',
    description: '对全场施加"麻痹"。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.7,
    buffId: 'debuff.paralyzed',
    buffDuration: 12,
    tags: ['thunder', 'aoe', 'debuff'],
  }),
  damageSkill({
    id: 'thunder.tempest',
    name: '雷暴',
    description: '敌人不少于 2 名时的高效群攻。',
    gcdCost: GCD.HEAVY,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.35,
    condition: when.enemiesAtLeast(2),
    tags: ['thunder', 'aoe'],
  }),
];

/** 流派 6：秩序 — 治疗与增益 */
const orderSkills = [
  healSkill({
    id: 'order.mend',
    name: '愈合',
    description: '小幅恢复自身生命。',
    gcdCost: GCD.NORMAL,
    ratio: 0.12,
    tags: ['order', 'heal'],
  }),
  healSkill({
    id: 'order.restoration',
    name: '复元',
    description: '中等治疗，硬直较长。',
    gcdCost: GCD.SLOW,
    ratio: 0.22,
    tags: ['order', 'heal'],
  }),
  healSkill({
    id: 'order.emergencyCare',
    name: '紧急救护',
    description: '仅在生命低于 50% 时可用，治疗量高。',
    gcdCost: GCD.NORMAL,
    ratio: 0.3,
    condition: when.hpBelow(0.5),
    tags: ['order', 'heal', 'emergency'],
  }),
  healSkill({
    id: 'order.lastRites',
    name: '临终祷言',
    description: '生命低于 25% 时的救命治疗。',
    gcdCost: GCD.SLOW,
    ratio: 0.45,
    condition: when.hpBelow(0.25),
    tags: ['order', 'heal', 'emergency'],
  }),
  damageBuffSkill({
    id: 'order.smite',
    name: '惩击',
    description: '造成伤害并为自身附加"祝福"。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.15,
    buffId: 'buff.blessed',
    buffDuration: 16,
    buffOnTarget: false,
    tags: ['order', 'buff'],
  }),
  damageSkill({
    id: 'order.judgmentStrike',
    name: '裁决',
    description: '持有"祝福"时倍率提升。',
    gcdCost: GCD.NORMAL,
    multiplier: 1.85,
    condition: when.hasBuff('buff.blessed'),
    tags: ['order', 'combo'],
  }),
  damageBuffSkill({
    id: 'order.fortify',
    name: '坚壁',
    description: '为自身附加强力减伤。',
    gcdCost: GCD.NORMAL,
    multiplier: 0.6,
    buffId: 'buff.fortified',
    buffDuration: 20,
    buffOnTarget: false,
    tags: ['order', 'defensive'],
  }),
  damageSkill({
    id: 'order.consecrate',
    name: '圣化',
    description: '对全部敌人造成秩序伤害。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.92,
    tags: ['order', 'aoe'],
  }),
  damageSkill({
    id: 'order.retribution',
    name: '天谴',
    description: '重型秩序单体攻击。',
    gcdCost: GCD.HEAVY,
    multiplier: 2.45,
    tags: ['order', 'heavy'],
  }),
  damageBuffSkill({
    id: 'order.sanctify',
    name: '涤罪',
    description: '削弱全部敌人。',
    gcdCost: GCD.SLOW,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.65,
    buffId: 'debuff.weakened',
    buffDuration: 16,
    tags: ['order', 'aoe', 'debuff'],
  }),
];

/**
 * oGCD 技能（30 个）。
 * 不占 GCD，有独立冷却，由槽位优先级决定抢占顺序（裁决 3）。
 */
const ogcdSkills = [
  // 爆发类
  damageSkill({
    id: 'ogcd.suddenStrike',
    name: '突袭',
    description: '短冷却的额外伤害。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.SHORT,
    multiplier: 1.5,
    priority: 30,
    tags: ['ogcd', 'burst'],
  }),
  damageSkill({
    id: 'ogcd.assassinate',
    name: '暗杀',
    description: '目标残血时的处决技。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 3.5,
    priority: 90,
    condition: when.targetHpBelow(0.25),
    tags: ['ogcd', 'execute'],
  }),
  damageSkill({
    id: 'ogcd.meteor',
    name: '陨星',
    description: '长冷却的全场高额伤害。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 2.2,
    priority: 60,
    tags: ['ogcd', 'aoe', 'burst'],
  }),
  damageSkill({
    id: 'ogcd.cataclysm',
    name: '天灾',
    description: '终极群体爆发。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.ULTIMATE,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 4.0,
    priority: 70,
    tags: ['ogcd', 'aoe', 'ultimate'],
  }),
  damageSkill({
    id: 'ogcd.deathSentence',
    name: '死刑宣告',
    description: '终极单体爆发。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.ULTIMATE,
    multiplier: 6.0,
    priority: 75,
    tags: ['ogcd', 'ultimate'],
  }),
  damageSkill({
    id: 'ogcd.multistrike',
    name: '多重打击',
    description: '随机敌人高倍打击。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.SHORT,
    range: SKILL_RANGE.RANDOM_ENEMY,
    multiplier: 2.0,
    priority: 25,
    tags: ['ogcd', 'random'],
  }),
  damageSkill({
    id: 'ogcd.crushingBlow',
    name: '碎击',
    description: '中冷却单体爆发。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 2.8,
    priority: 40,
    tags: ['ogcd', 'burst'],
  }),
  damageSkill({
    id: 'ogcd.desperateSurge',
    name: '殊死一击',
    description: '生命低于 30% 时的高倍反击。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 3.6,
    priority: 85,
    condition: when.hpBelow(0.3),
    tags: ['ogcd', 'desperate'],
  }),
  damageSkill({
    id: 'ogcd.swarmVolley',
    name: '群射',
    description: '敌人较多时的群体爆发。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.8,
    priority: 55,
    condition: when.enemiesAtLeast(3),
    tags: ['ogcd', 'aoe'],
  }),
  damageSkill({
    id: 'ogcd.lateGameNova',
    name: '终末新星',
    description: '战斗 60 秒后解锁的全场爆发。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 3.0,
    priority: 65,
    condition: when.afterSeconds(60),
    tags: ['ogcd', 'aoe', 'lategame'],
  }),

  // 治疗类
  healSkill({
    id: 'ogcd.secondWind',
    name: '振奋',
    description: '短冷却自我治疗。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.SHORT,
    ratio: 0.15,
    priority: 50,
    condition: when.hpBelow(0.7),
    tags: ['ogcd', 'heal'],
  }),
  healSkill({
    id: 'ogcd.emergencyHeal',
    name: '应急治疗',
    description: '生命低于 40% 时立即恢复。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    ratio: 0.3,
    priority: 95,
    condition: when.hpBelow(0.4),
    tags: ['ogcd', 'heal', 'emergency'],
  }),
  healSkill({
    id: 'ogcd.fullRestore',
    name: '完全复元',
    description: '生命危急时的大治疗。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    ratio: 0.55,
    priority: 99,
    condition: when.hpBelow(0.25),
    tags: ['ogcd', 'heal', 'emergency'],
  }),
  healSkill({
    id: 'ogcd.phoenixGrace',
    name: '不死鸟之恩',
    description: '终极治疗，濒死时使用。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.ULTIMATE,
    ratio: 0.9,
    priority: 100,
    condition: when.hpBelow(0.15),
    tags: ['ogcd', 'heal', 'ultimate'],
  }),
  healSkill({
    id: 'ogcd.steadyRecovery',
    name: '稳步恢复',
    description: '无条件的稳定治疗。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    ratio: 0.2,
    priority: 45,
    tags: ['ogcd', 'heal'],
  }),

  // 增益类
  damageBuffSkill({
    id: 'ogcd.warcry',
    name: '战吼',
    description: '为自身叠加战意。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 0.5,
    buffId: 'blade.momentum',
    stacks: 2,
    buffDuration: 16,
    buffOnTarget: false,
    priority: 35,
    tags: ['ogcd', 'buff'],
  }),
  damageBuffSkill({
    id: 'ogcd.battleTrance',
    name: '战斗恍惚',
    description: '长时间的强力增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    multiplier: 0.5,
    buffId: 'buff.trance',
    stacks: 1,
    buffDuration: 30,
    buffOnTarget: false,
    priority: 58,
    tags: ['ogcd', 'buff'],
  }),
  damageBuffSkill({
    id: 'ogcd.ironWill',
    name: '铁壁意志',
    description: '强力减伤，受创时优先使用。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 0.3,
    buffId: 'buff.fortified',
    stacks: 2,
    buffDuration: 20,
    buffOnTarget: false,
    priority: 80,
    condition: when.hpBelow(0.6),
    tags: ['ogcd', 'defensive'],
  }),
  damageBuffSkill({
    id: 'ogcd.blazingSoul',
    name: '炽魂',
    description: '火系增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 0.6,
    buffId: 'buff.blazing',
    stacks: 2,
    buffDuration: 20,
    buffOnTarget: false,
    priority: 38,
    tags: ['ogcd', 'buff', 'fire'],
  }),
  damageBuffSkill({
    id: 'ogcd.staticCharge',
    name: '蓄电',
    description: '雷系增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.SHORT,
    multiplier: 0.6,
    buffId: 'buff.charged',
    stacks: 2,
    buffDuration: 16,
    buffOnTarget: false,
    priority: 36,
    tags: ['ogcd', 'buff', 'thunder'],
  }),
  damageBuffSkill({
    id: 'ogcd.divineFavor',
    name: '神恩',
    description: '秩序系强力增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    multiplier: 0.5,
    buffId: 'buff.blessed',
    stacks: 3,
    buffDuration: 24,
    buffOnTarget: false,
    priority: 52,
    tags: ['ogcd', 'buff', 'order'],
  }),
  damageBuffSkill({
    id: 'ogcd.shadowVeil',
    name: '影纱',
    description: '暗影系防御增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 0.4,
    buffId: 'buff.shrouded',
    stacks: 2,
    buffDuration: 20,
    buffOnTarget: false,
    priority: 42,
    tags: ['ogcd', 'defensive', 'shadow'],
  }),
  damageBuffSkill({
    id: 'ogcd.frozenBastion',
    name: '冰垒',
    description: '霜系防御增益。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 0.4,
    buffId: 'buff.frostArmor',
    stacks: 2,
    buffDuration: 20,
    buffOnTarget: false,
    priority: 44,
    tags: ['ogcd', 'defensive', 'frost'],
  }),

  // 减益类
  damageBuffSkill({
    id: 'ogcd.crippling',
    name: '致残打击',
    description: '大幅削弱目标。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 1.2,
    buffId: 'debuff.weakened',
    stacks: 2,
    buffDuration: 20,
    priority: 33,
    tags: ['ogcd', 'debuff'],
  }),
  damageBuffSkill({
    id: 'ogcd.massBrittle',
    name: '全域脆化',
    description: '对全场施加脆化。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.8,
    buffId: 'debuff.brittle',
    stacks: 2,
    buffDuration: 20,
    priority: 48,
    tags: ['ogcd', 'aoe', 'debuff'],
  }),
  damageBuffSkill({
    id: 'ogcd.plague',
    name: '瘟疫',
    description: '对全场施加衰败。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 0.9,
    buffId: 'debuff.decay',
    stacks: 2,
    buffDuration: 24,
    priority: 46,
    tags: ['ogcd', 'aoe', 'debuff'],
  }),
  damageBuffSkill({
    id: 'ogcd.infernalMark',
    name: '炼狱印记',
    description: '强化引燃效果。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 1.0,
    buffId: 'debuff.burning',
    stacks: 3,
    buffDuration: 20,
    priority: 34,
    tags: ['ogcd', 'debuff', 'fire'],
  }),

  // 吸血类
  drainSkill({
    id: 'ogcd.bloodfeast',
    name: '血宴',
    description: '高倍吸血，残血时优先。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.MID,
    multiplier: 2.2,
    drainRatio: 0.8,
    priority: 78,
    condition: when.hpBelow(0.5),
    tags: ['ogcd', 'drain'],
  }),
  drainSkill({
    id: 'ogcd.massDrain',
    name: '群体汲取',
    description: '对全场吸血。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.LONG,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.6,
    drainRatio: 0.4,
    priority: 56,
    tags: ['ogcd', 'aoe', 'drain'],
  }),

  // 控场类
  damageBuffSkill({
    id: 'ogcd.absoluteZero',
    name: '绝对零度',
    description: '冻结全场敌人，大幅削弱其攻防。敌人较多时才值得一用。',
    type: SKILL_TYPE.OGCD,
    cooldown: CD.ULTIMATE,
    range: SKILL_RANGE.ALL_ENEMIES,
    multiplier: 1.4,
    buffId: 'debuff.chilled',
    stacks: 3,
    buffDuration: 24,
    priority: 62,
    condition: when.enemiesAtLeast(2),
    tags: ['ogcd', 'aoe', 'debuff', 'frost'],
  }),
];

export const OFFICIAL_SKILLS = [
  ...bladeSkills,
  ...fireSkills,
  ...frostSkills,
  ...shadowSkills,
  ...thunderSkills,
  ...orderSkills,
  ...ogcdSkills,
];

export const GCD_SKILL_COUNT =
  bladeSkills.length +
  fireSkills.length +
  frostSkills.length +
  shadowSkills.length +
  thunderSkills.length +
  orderSkills.length;

export const OGCD_SKILL_COUNT = ogcdSkills.length;
